apiVersion: v1
kind: ConfigMap
metadata:
  namespace: spring-cloud-dataflow
  name: grafana
  labels:
    app: grafana
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: ScdfPrometheus
      type: prometheus
      access: proxy
      org_id: 1
      url: http://10.43.29.225:9090
      is_default: true
      version: 5
      editable: true
      read_only: false
