apiVersion: v1
kind: Service
metadata:
  namespace: spring-cloud-dataflow
  name: skipper
  labels:
    app: skipper
    spring-deployment-id: scdf
spec:
  # If you are running k8s on a local dev box, using minikube, or Kubernetes on docker desktop you can use type NodePort instead
  type: LoadBalancer
  ports:
  - port: 8092
    targetPort: 7577
  selector:
    app: skipper
